apiVersion: vmoperator.vmware.com/v1alpha5
kind: VirtualMachine
metadata:
  name: vm-01-argotest
  labels:
    vm-selector: vm-01-argotest
spec:
  className: best-effort-small
  # Friendly image name: ubuntu-24.04-server-cloudimg-amd64
  imageName: ubuntu-24.04-server-cloudimg-amd64
  storageClass: cluster-mgmt-01a-optimal-datastore-default-policy-autoraid
  powerState: PoweredOff
  network:
    hostName: vm-01-argotest
  bootstrap:
    cloudInit:
      rawCloudConfig:
        name: vm-01-argotest-bootstrap-secret
        key: user-data
